### PR TITLE
Fix bugs: Add duplicate m/ prefix validation and joinDate validation

### LINKED ISSUE #172: Fix bugs regarding joindate and input validation of pay/unpay
Ensure that join date cannot be set to a date after the first payment date, so that data discrepancies would not occur where there are dates with payment made even before user join date.
Ensure that for pay and unpay method, only accepts one prefix m/[month]. Current implementation allows for multiple prefixes, but only accepts the final one, which might make it confusing for the user.

### PR DESCRIPTION
**Pull request by leechongrui**
- Add duplicate prefix validation for m/ in PaymentCommandParser and UnpayCommandParser to prevent users from accidentally entering multiple month values

- Add joinDate validation in EditCommand to prevent setting joinDate after existing payment history records, ensuring data integrity

Fixes #172

### CODE REVIEW

File: src/main/java/seedu/tutorpal/logic/parser/UnpayCommandParser.java [hunk 1]
```diff
@@ -33,6 +33,8 @@ public class UnpayCommandParser implements Parser<UnpayCommand> {
     public UnpayCommand parse(String args) throws ParseException {
         ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(args, PREFIX_PAYMENT_MONTH);
 
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_PAYMENT_MONTH);
```
Comment (siangjun2) [inline src/main/java/seedu/tutorpal/logic/parser/UnpayCommandParser.java]: Good catch, I'll have to add this to Mark too
