### PR TITLE
Complete tag removal and fix remaining issues

### LINKED ISSUE #96: Remove Tag Command

### PR DESCRIPTION
**Pull request by leechongrui**
- Make JsonAdaptedPaymentHistory public for test access
- Fix import order in AddCommand and ParserUtilTest
- Remove unused INVALID_TAG constant from JsonAdaptedPersonTest
- All tag functionality completely removed from codebase
- Build successful with all tests passing
Fixes #96

### CODE REVIEW

File: src/test/java/seedu/tutorpal/testutil/TypicalPersons.java [hunk 1]
```diff
@@ -12,8 +12,6 @@
 import static seedu.tutorpal.logic.commands.CommandTestUtil.VALID_PHONE_BOB;
 import static seedu.tutorpal.logic.commands.CommandTestUtil.VALID_ROLE_AMY;
 import static seedu.tutorpal.logic.commands.CommandTestUtil.VALID_ROLE_BOB;
-import static seedu.tutorpal.logic.commands.CommandTestUtil.VALID_TAG_FRIEND;
-import static seedu.tutorpal.logic.commands.CommandTestUtil.VALID_TAG_HUSBAND;
```
Comment (lvbrobinhood) [inline src/test/java/seedu/tutorpal/testutil/TypicalPersons.java]: Good catch, very comprehensive removal of tags

File: src/test/java/seedu/tutorpal/logic/parser/ParserUtilTest.java [hunk 2]
```diff
@@ -147,50 +137,4 @@ public void parseEmail_validValueWithWhitespace_returnsTrimmedEmail() throws Exc
         Email expectedEmail = new Email(VALID_EMAIL);
         assertEquals(expectedEmail, ParserUtil.parseEmail(emailWithWhitespace));
     }
-
-    @Test
```
Comment (lvbrobinhood) [inline src/test/java/seedu/tutorpal/logic/parser/ParserUtilTest.java]: Good to remove tests that are no longer relevant

File: src/test/java/seedu/tutorpal/logic/parser/ParserUtilTest.java [hunk 3]
```diff
@@ -1,38 +1,28 @@
...
-import static org.junit.jupiter.api.Assertions.assertTrue;
 import static seedu.tutorpal.logic.parser.ParserUtil.MESSAGE_INVALID_INDEX;
 import static seedu.tutorpal.testutil.Assert.assertThrows;
 import static seedu.tutorpal.testutil.TypicalIndexes.INDEX_FIRST_PERSON;
 
-import java.util.Arrays;
-import java.util.Collections;
-import java.util.HashSet;
-import java.util.Set;
-
```
Comment (lvbrobinhood) [inline src/test/java/seedu/tutorpal/logic/parser/ParserUtilTest.java]: Removing unused imports is good practice

File: src/main/java/seedu/tutorpal/logic/parser/ParserUtil.java [hunk 4]
```diff
@@ -140,45 +138,4 @@ public static Set<Class> parseClasses(Collection<String> classes) throws ParseEx
         return classSet;
     }
 
-    /**
-     * Parses a {@code String tag} into a {@code Tag}.
-     * Leading and trailing whitespaces will be trimmed.
```
Comment (lvbrobinhood) [inline src/main/java/seedu/tutorpal/logic/parser/ParserUtil.java]: Good removal of redundant methods
